/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Content: (typeof import('../views/layout/components/mains/model-default.vue'))['default']
    copy: (typeof import('../views/layout/components/main-free/index.vue'))['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FreeContent: typeof import('./../views/layout/components/main-free/free-content.vue')['default']
    Icon: typeof import('./../components/base/icon/index.vue')['default']
    ImageEmpty: typeof import('./../components/base/image-empty/index.vue')['default']
    MainFree: typeof import('./../views/layout/components/main-free/index.vue')['default']
    Mains: typeof import('./../views/layout/components/mains/index.vue')['default']
    MainsContent: (typeof import('../views/layout/components/mains/model-default.vue'))['default']
    ModelDefault: typeof import('./../views/layout/components/mains/model-default.vue')['default']
    ModelFree: typeof import('./../views/layout/components/main-free/model-free.vue')['default']
    ModelInput: typeof import('./../components/model-input/index.vue')['default']
    ModelInputSetting: typeof import('./../components/model-input/model-input-setting.vue')['default']
    Navbar: typeof import('./../views/layout/components/navbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./../views/layout/components/settings/index.vue')['default']
  }
}
